# @package _global_
model:
  name: convnext_base
  architecture: convnext
  pretrained: true
  weights: IMAGENET1K_V1
  hook_layer: avgpool
  
  training:
    batch_size: 16
    learning_rate: 0.0001
    gradient_accumulation_steps: 4





