# @package _global_
model:
  name: mixer_l16
  architecture: mixer
  pretrained: true
  weights: mixer_l16_224.goog_in21k_ft_in1k
  hook_layer: head
  requires_timm: true
  
  training:
    batch_size: 8
    learning_rate: 0.0001
    gradient_accumulation_steps: 4





