# @package _global_
model:
  name: vit_l_32
  architecture: vit
  pretrained: true
  weights: IMAGENET1K_V1
  hook_layer: heads.head
  
  training:
    batch_size: 32
    learning_rate: 0.0001
    gradient_accumulation_steps: 1





